version: '3.4'

networks:
    sachdemoapp:

services:
    sachdemoapp:
        container_name: sach-demo-app-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
                - 8002:1433
        environment:
                    - ACCEPT_EULA=Y
                    - SA_PASSWORD=password@12345#
        networks:
        - sachdemoapp

    testproject.webapi:
        container_name: sach-demo-app
        image: ${DOCKER_REGISTRY-}testprojectwebapi
        build:
          context: .
          dockerfile: TestProject.WebAPI/Dockerfile
        ports: 
            - 8001:80
        depends_on:
            - demoappdb
        environment:
            - DB_HOST=sachdemoapp
            - DB_NAME=testprojectwebapi
            - DB_SA_PASSWORD=password@12345#
        networks:
        - sachdemoapp